name: deploy-gh-pages
run-name: Pushing subtree onto `gh-pages`
on:
  push:
    branches:
      - master
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git remote add origin https://github.com/KCL-DreiKlite/kcl-dreiklite.github.io.git
      - run: git subtree push --prefix dist origin gh-pages
