name: deploy-gh-pages
run-name: Pushing subtree onto `gh-pages`
on:
  push:
    branches:
      - master
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all remote branches first
        run: git fetch --all
      - name: Show branches
        run: git branch -a
      - name: Push subtree onto `gh-pages`
        run: git subtree push --prefix dist origin gh-pages
