name: deploy-gh-pages
run-name: Pushing subtree onto `gh-pages`
on:
  push:
    branches:
      - master
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show branches
        run: git branch -a
      - name: Push subtree onto `gh-pages`
        run: git push origin `git subtree split --prefix dist master`:gh-pages --force
